server:
  port: 80

spring:
  thymeleaf:
    # 关闭 thymeleaf 缓存
    cache: false
  datasource:
    username: root
    password: 123456
    #url: jdbc:mysql://192.168.23.129:3306/study-security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://127.0.0.1:3306/study-security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

mengxuegu:
  security:
    authentication:
      loginPage: /login/page              # 响应认证（登录页面）页面的URL
      loginProcessingUrl: /login/form     # 登录表单提交 处理的URL
      usernameParameter: name             # 登录表单提交的用户名的属性名
      passwordParameter: pwd              # 登录表单提交的密码的属性名
      staticPaths:                        # 静态资源
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT                 # 认证之后 响应的类型：JSON/REDIRECT
      imageCodeUrl: /code/image # 获取图形验证码地址
      mobileCodeUrl: /code/mobile # 获取手机验证码地址
      mobilePage: /mobile/page # 前往手机登录页面
      tokenValiditySeconds: 604800 #记住我功能有效时常